# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-16 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_avatar',
            name='avatar',
            field=models.ImageField(upload_to='avatar'),
        ),
    ]
