# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='last_modified_time')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='status')),
                ('abstract', models.CharField(blank=True, help_text='optional,the first 60 characters if empty', max_length=60, null=True, verbose_name='abstract')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='likes')),
                ('imgurl', models.CharField(blank=True, max_length=255, null=True, verbose_name='imgurl')),
                ('topped', models.BooleanField(default=False, verbose_name='topped')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_modified_time'],
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='category_name')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='last_modified_time')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog_Module.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Blog_Module.Tag'),
        ),
    ]
