# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-20 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='property',
            field=models.CharField(choices=[('o', 'Original'), ('r', 'Reprint')], default='r', max_length=1, verbose_name='property'),
        ),
    ]
